[package]
name = "axum_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", features = ["macros", "multipart", "ws"] } 
tower-http = { version = "0.6.1", features = ["full"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.24.0"
bcrypt = "0.15.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cookie = "0.18.1"
jsonwebtoken = "9.3.0"
chrono = "0.4.38"
headers = "0.4.0"
reqwest = { version = "0.12", features = ["json"] }
sqlx = { version = "0.8.3", features = ["macros", "postgres", "runtime-tokio", "time"] }
dotenv = "0.15.0"
rand = "0.8.5"
uuid = { version = "1.11.1", features = ["v4"] }
